name: Release
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          depth: 0
      - name: Recursive submodule update
        run: git submodule update --init --recursive
      - name: setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.6
      - uses: bufbuild/buf-setup-action@v0.3.1
      - uses: bufbuild/buf-push-action@v0.3.0
        with:
          input: 'proto'
          buf_token: ${{ secrets.BUF_TOKEN }}    
