name: Release
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          depth: submodules
      - name: Recursive submodule update
        run: git submodule update --init --recursive
      - name: setup
        uses: actions/setup-go@v1
        with:
          go-version: '1.17'
      - uses: bufbuild/buf-setup-action@v0.6.0
      - uses: bufbuild/buf-push-action@v1
        with:
          input: 'third_party'
          buf_token: ${{ secrets.BUF_TOKEN }}    
